apiVersion: v1
kind: ConfigMap
metadata:
  name: ecoloop-ai-service-config
  namespace: default
  labels:
    app: ecoloop-ai-service
data:
  LOG_LEVEL: "info"
  AWS_REGION: "us-east-1"
  MODEL_PATH: "best.pt"
